services:
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

  book-service:
    build:
      context: ./services/book
      dockerfile: Dockerfile.book  # Ensure this file exists in ./services/book
    ports:
      - "50051:50051"
    networks:
      - microservices-network

  user-service:
    build:
      context: ./services/user
      dockerfile: Dockerfile.user  # Ensure this file exists in ./services/user
    ports:
      - "50052:50052"
    networks:
      - microservices-network

  review-service:
    build:
      context: ./services/review
      dockerfile: Dockerfile.review  # Ensure this file exists in ./services/review
    ports:
      - "50053:50053"
    networks:
      - microservices-network


networks:
  microservices-network:
    driver: bridge

volumes:
  db:
