global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'book-service'
    static_configs:
      - targets: ['book-service:2111']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:2112']

  - job_name: 'review-service'
    static_configs:
      - targets: ['review-service:2113']
